<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Household Masterlist Report</title>
    <style>
        @page {
            margin: 15mm 15mm 25mm 15mm;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 10pt;
            line-height: 1.4;
            color: #000;
            margin: 0;
            padding: 0;
        }

        /* Header Styles */
        .report-header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
        }

        .report-header .line {
            margin: 2px 0;
            font-size: 10pt;
        }

        .report-header .title {
            font-size: 14pt;
            font-weight: bold;
            margin: 8px 0;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .report-header .meta {
            font-size: 9pt;
            margin-top: 5px;
            color: #333;
        }

        /* Section Styles */
        .section {
            margin: 20px 0;
        }

        .section-title {
            font-size: 11pt;
            font-weight: bold;
            margin: 15px 0 10px 0;
            padding-bottom: 5px;
            border-bottom: 1px solid #333;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
            font-size: 9pt;
        }

        table thead {
            background-color: #f0f0f0;
        }

        table th {
            padding: 6px 4px;
            text-align: left;
            border: 1px solid #000;
            font-weight: bold;
            background-color: #e0e0e0;
            font-size: 9pt;
        }

        table td {
            padding: 5px 4px;
            border: 1px solid #000;
            font-size: 8pt;
        }

        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Household Block */
        .household-block {
            margin: 20px 0;
            padding: 10px;
            border: 1px solid #333;
            page-break-inside: avoid;
        }

        .household-block-title {
            font-size: 11pt;
            font-weight: bold;
            margin-bottom: 8px;
            background-color: #e0e0e0;
            padding: 5px;
        }

        .household-info {
            margin: 8px 0;
            font-size: 9pt;
        }

        .household-info-row {
            margin: 3px 0;
        }

        .household-info-label {
            font-weight: bold;
            display: inline-block;
            width: 150px;
        }

        /* Footer Styles */
        .report-footer {
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #333;
            font-size: 9pt;
        }

        .signature-section {
            display: flex;
            justify-content: space-around;
            margin-top: 30px;
            margin-bottom: 20px;
        }

        .signature-box {
            text-align: center;
            width: 200px;
        }

        .signature-line {
            border-top: 1px solid #000;
            width: 180px;
            margin: 40px auto 5px;
            height: 1px;
        }

        .signature-label {
            font-weight: bold;
            margin-top: 5px;
        }

        .page-number {
            text-align: center;
            font-size: 9pt;
            margin-top: 10px;
            color: #666;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }
    </style>
</head>

<body>
    <!-- Header -->
    <div class="report-header">
        <div class="line">Republic of the Philippines</div>
        <div class="line">Province of {{ $barangay_info['province'] ?? 'Capiz' }}</div>
        <div class="line">Municipality of {{ $barangay_info['municipality'] ?? 'Ivisan' }}</div>
        <div class="line">Barangay {{ $barangay_info['name'] ?? 'Poblacion Sur' }}</div>
        <div class="title">HOUSEHOLD MASTERLIST REPORT</div>
        <div class="meta">
            Date Generated: {{ $generated_date ?? date('F d, Y') }}<br>
            Generated by: {{ $generated_by ?? 'System' }}
        </div>
    </div>

    <!-- SECTION 1: Household Summary Table -->
    <div class="section">
        <div class="section-title">SECTION 1 – Household Summary</div>
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">No.</th>
                    <th style="width: 10%;">Household ID</th>
                    <th style="width: 18%;">Head of Household</th>
                    <th style="width: 12%;">Purok</th>
                    <th style="width: 20%;">Complete Address</th>
                    <th style="width: 8%;">Total Members</th>
                    <th style="width: 12%;">Date Registered</th>
                    <th style="width: 8%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($households as $index => $household)
                    <tr>
                        <td style="text-align: center;">{{ $index + 1 }}</td>
                        <td style="text-align: center;">{{ $household->id }}</td>
                        <td>{{ $household->head_name ?? ($household->headResident ? $household->headResident->full_name : 'N/A') }}
                        </td>
                        <td>{{ $household->purok->name ?? 'N/A' }}</td>
                        <td>{{ $household->address ?? 'N/A' }}</td>
                        <td style="text-align: center;">{{ $household->residents->count() ?? 0 }}</td>
                        <td style="text-align: center;">
                            {{ $household->created_at ? \Carbon\Carbon::parse($household->created_at)->format('M d, Y') : 'N/A' }}
                        </td>
                        <td style="text-align: center;">Active</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" style="text-align: center; padding: 20px;">
                            No households found
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>


    <!-- Footer -->
    <div class="report-footer">
        <div class="signature-section">
            <div class="signature-box">
                <div class="signature-line"></div>
                <div class="signature-label">Prepared by</div>
            </div>
            <div class="signature-box">
                <div class="signature-line"></div>
                <div class="signature-label">Reviewed by</div>
            </div>
            <div class="signature-box">
                <div class="signature-line"></div>
                <div class="signature-label">Approved by</div>
            </div>
        </div>
        <div style="text-align: center; margin-top: 20px;">
            <div
                style="width: 80px; height: 80px; margin: 0 auto; border: 2px solid #000; display: flex; align-items: center; justify-content: center; font-size: 10pt; color: #999;">
                Barangay<br>Seal
            </div>
        </div>
        <div class="page-number">
            Page <span class="pagenum"></span>
        </div>
    </div>

    <script type="text/php">
        if (isset($pdf)) {
            $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
            $size = 9;
            $font = $fontMetrics->getFont("Arial");
            $width = $fontMetrics->get_text_width($text, $font, $size) / 2;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 20;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>

</html>
